-- insert into portal (id, name) values (1, 'Gulf bank retail banking');
--
-- insert into page (id, name, portal_id) values (1, 'login', 1);
--
-- insert into page (id, name, portal_id) values (2, 'accounts', 1);
--
-- insert into page (id, name, portal_id) values (3, 'profile', 1);
